apiVersion: v1
kind: Service
metadata:
  name: taskflow-app
  labels:
    app: taskflow-app
spec:
  type: NodePort
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30007
  selector:
    app: taskflow-app
